@startuml

class Calculator {
    - Stack<Double> numStack
    - Stack<String> opStack
    + calculate(sb: StringBuilder): double
    - calculateTwo(num1: double, num2: double, op: String): double
    - toSuffix(formula: ArrayList<Object>): ArrayList<Object>
    - prior(op1: String, op2: String): boolean
    - getPriority(op: String): int
    - toFormula(sb: StringBuilder): ArrayList<Object>
}

@enduml
